OBJS	= algo.o erroe.o i_c_d.o input_output.o lzw.o main.o quantization.o
SOURCE	= algo.c erroe.c i_c_d.c input_output.c lzw.c main.c quantization.c
HEADER	= algo.h erroe.h i_c_d.h input_output.h lzw.h quantization.h
OUT	= project
CC	 = gcc
FLAGS	 = -g -c -Wall
LFLAGS	 = 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

algo.o: algo.c
	$(CC) $(FLAGS) algo.c 

erroe.o: erroe.c
	$(CC) $(FLAGS) erroe.c 

i_c_d.o: i_c_d.c
	$(CC) $(FLAGS) i_c_d.c 

input_output.o: input_output.c
	$(CC) $(FLAGS) input_output.c 

lzw.o: lzw.c
	$(CC) $(FLAGS) lzw.c 

main.o: main.c
	$(CC) $(FLAGS) main.c 

quantization.o: quantization.c
	$(CC) $(FLAGS) quantization.c 


clean:
	rm -f $(OBJS) $(OUT)
